crypto_config:
  - domain: chainmaker.org
    host_name: wx-org
    count: n                # 如果为1，直接使用host_name，否则添加递增编号
    #    pk_algo: sm2
    pk_algo: ecc_p256
    ski_hash: sha256
    tls_mode: 0 # 0：单证书模式，1：双证书模式（国密tls标准需要双证书）
    #pkcs11配置
    pkcs11:
      enabled: false
      type: pkcs11 #support sdf | pkcs11
      library: /usr/local/lib64/pkcs11/libupkcs11.so
      label: HSM
      password: 11111111
      session_cache_size: 10
      hash: "SHA256" # hash algorithm used to compute SKI
    specs: &specs_ref
      expire_year:  10
      sans:
        - chainmaker.org
        - localhost
        - 127.0.0.1
    location: &location_ref
      country:            CN
      locality:           Beijing
      province:           Beijing
    # CA证书配置
    ca:
      location:
        <<: *location_ref
      specs:
        <<: *specs_ref
    # 节点证书配置
    node:
      - type: node
        # 共识节点数量
        count: 1
        # 共识节点配置
        location:
          <<: *location_ref
        specs:
          <<: *specs_ref
          expire_year:  5
    user:
      - type: client
        # 普通用户证书数量
        count: 5
        # 普通用户证书配置
        location:
          <<: *location_ref
        expire_year:  5